version: '3.8'

services:
  nutrition-agent-test:
    image: registry.cn-hangzhou.aliyuncs.com/big-head/nutrition-agent:latest
    container_name: nutrition-agent-test
    ports:
      - "8088:8000"
    volumes:
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - ENV=test
      - PDF_ANALYSIS_SUBMIT_URL=http://172.16.10.10:9050/food/view/intellectual-proxy/receivePdfResult
      - MEAL_PLAN_SUBMIT_URL=http://172.16.10.10:9050/food/view/intellectual-proxy/receiveFoodCustomizedResult
      - MEAL_PLAN_REPLACE_URL=http://172.16.10.10:9050/food/view/intellectual-proxy/receiveFoodCustomizedReplace

  nutrition-agent-dev:
    image: registry.cn-hangzhou.aliyuncs.com/big-head/nutrition-agent:latest
    container_name: nutrition-agent-dev
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - ENV=dev
      - PDF_ANALYSIS_SUBMIT_URL=http://172.16.10.148:9050/food/view/intellectual-proxy/receivePdfResult
      - MEAL_PLAN_SUBMIT_URL=http://172.16.10.148:9050/food/view/intellectual-proxy/receiveFoodCustomizedResult
      - MEAL_PLAN_REPLACE_URL=http://172.16.10.148:9050/food/view/intellectual-proxy/receiveFoodCustomizedReplace

  nutrition-agent-prod:
    image: registry.cn-hangzhou.aliyuncs.com/big-head/nutrition-agent:latest
    container_name: nutrition-agent-prod
    ports:
      - "8089:8000"
    volumes:
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - ENV=prod
      - PDF_ANALYSIS_SUBMIT_URL=http://172.16.0.100:9050/food/view/intellectual-proxy/receivePdfResult
      - MEAL_PLAN_SUBMIT_URL=http://172.16.0.100:9050/food/view/intellectual-proxy/receiveFoodCustomizedResult
      - MEAL_PLAN_REPLACE_URL=http://172.16.0.100:9050/food/view/intellectual-proxy/receiveFoodCustomizedReplace
