version: '3.8'

services:
  nutrition-agent:
    build: .
    # image: registry.cn-hangzhou.aliyuncs.com/big-head/nutrition_agent:latest
    image: registry.cn-hangzhou.aliyuncs.com/big-head/nutrition_agent:test  
    container_name: nutrition-agent
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    restart: unless-stopped
